# Generated by Django 4.1.6 on 2023-04-16 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playtime', '0002_alter_playmodels_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abount', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='playmodels',
            name='date',
        ),
        migrations.AddField(
            model_name='playmodels',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playmodels',
            name='main_play',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='play', to='playtime.play'),
            preserve_default=False,
        ),
    ]
