# Generated by Django 4.1.6 on 2023-04-16 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playtime', '0003_play_remove_playmodels_date_playmodels_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='play',
            old_name='abount',
            new_name='about',
        ),
    ]
